version: '3.8'
services:
    discord-spicy-bot:
        container_name: discord
        env_file: '.env.local'
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - sqlite-data:/app/db
        restart: unless-stopped

volumes:
    sqlite-data:
        driver: local
