export {
    CARD_COLORS as LEVEL_CARD_COLORS,
    CARD_FONT_BOLD_URL as LEVEL_CARD_FONT_BOLD_URL,
    CARD_FONT_REGULAR_URL as LEVEL_CARD_FONT_REGULAR_URL,
    CARD_OUTER_PADDING as LEVEL_CARD_OUTER_PADDING,
    CARD_PANEL_PADDING as LEVEL_CARD_PANEL_PADDING,
    CARD_WIDTH as LEVEL_CARD_WIDTH,
} from '../shared/cardTheme';

export const LEVEL_CARD_HEIGHT = 280;

export const LEVEL_CARD_AVATAR_SIZE = 160;
export const LEVEL_CARD_AVATAR_BORDER = 5;
