import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import { createClient } from '@hey-api/openapi-ts';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { SDK_GENERATOR_CONFIG } from '../openapi-ts.config';

/**
 * The drift gate between the committed spec and the committed SDK.
 *
 * `openApiSpec.test.ts` holds the spec to the routes; this holds `src/gen` to the spec.
 * Together they mean a route changed without `pnpm sdk:generate` fails the suite, rather
 * than leaving the dashboard compiling against the API as it was.
 *
 * It regenerates from the committed spec with the CLI's own config into a temp directory
 * and compares file by file, both ways: a file missing, a file extra, a file different.
 * It sits outside `src` because it runs under Node, beside the config it exercises:
 * `src` is type-checked without Node types (`tsconfig.json`), this file by
 * `tsconfig.node.json`.
 *
 * Only the output path and the logs are overridden, and neither changes a generated byte:
 * the logs are silenced, and `file: false` keeps a failed run from dropping a log file in
 * the cwd. Line endings are normalised for the same reason `openApiSpec.test.ts` compares
 * parsed JSON: a checkout that turns them into CRLF is not a stale SDK.
 *
 * Two things it cannot see, or sees differently:
 *  - A generated file on disk that git does not track — the test reads the working tree.
 *    `pnpm sdk:check` (`git status --porcelain`) still covers that.
 *  - Which dependency versions the generator reads. Called from code, it looks for a
 *    `package.json` from the cwd (the repo root under Vitest); the CLI reads this
 *    package's. Today that only picks the `zod` import, and both declare the same zod.
 *    If they ever disagree, this test fails in a way `pnpm sdk:generate` cannot fix —
 *    align the two `zod` ranges.
 */

const REMEDY =
    'The committed SDK in packages/web-sdk/src/gen is not what the committed spec generates. ' +
    'Run `pnpm sdk:generate` and commit the result.';

/** Every file under `root`, keyed by its `/`-separated path relative to `root`. */
function readTree(root: string): Map<string, string> {
    const entries = readdirSync(root, { recursive: true, withFileTypes: true })
        .filter((entry) => entry.isFile())
        .map((entry) => {
            const path = join(entry.parentPath, entry.name);
            const key = relative(root, path).split('\\').join('/');
            return [key, readFileSync(path, 'utf8').replaceAll('\r\n', '\n')] as const;
        });
    return new Map(entries);
}

describe('generated SDK drift', () => {
    let regeneratedRoot: string;

    beforeAll(async () => {
        regeneratedRoot = mkdtempSync(join(tmpdir(), 'web-sdk-gen-'));
        await createClient({
            ...SDK_GENERATOR_CONFIG,
            output: { ...SDK_GENERATOR_CONFIG.output, path: regeneratedRoot },
            logs: { level: 'silent', file: false },
        });
        // A hook gets Vitest's 10s hook budget, not the raised `testTimeout`; generation is
        // ~0.3s warm, but a cold cache under parallel load is where this suite flakes.
    }, 20_000);

    afterAll(() => {
        rmSync(regeneratedRoot, { recursive: true, force: true });
    });

    it('matches what the committed spec generates', () => {
        const committed = readTree(SDK_GENERATOR_CONFIG.output.path);
        const regenerated = readTree(regeneratedRoot);
        // The generator answers an unreadable spec with no files rather than an error, and
        // an empty regeneration would read as every committed file being "extra" — a stale
        // SDK rather than a generator that did nothing.
        expect(regenerated.size, 'The generator wrote no files. Is the committed spec readable?').toBeGreaterThan(0);

        const missing = [...regenerated.keys()].filter((file) => !committed.has(file));
        const extra = [...committed.keys()].filter((file) => !regenerated.has(file));
        const different = [...regenerated.keys()].filter(
            (file) => committed.has(file) && committed.get(file) !== regenerated.get(file)
        );

        expect({ missing, extra, different }, REMEDY).toEqual({ missing: [], extra: [], different: [] });
    });
});
