export const WARNING_TIMEZONE = 'America/Los_Angeles';
export const WARNING_DEFAULT_DURATION_MONTHS = 6;
export const WARNING_DATE_PLACEHOLDER = 'YYYY-MM-DD';

export const WARN_RULE_MAX_LENGTH = 100;
export const WARN_DESCRIPTION_MAX_LENGTH = 1000;
export const WARN_DATE_INPUT_MAX_LENGTH = 10;

export const WARNING_SLUG_BASE_MAX_LENGTH = 32;
export const WARNING_SLUG_SUFFIX_LENGTH = 4;
export const WARNING_SLUG_INSERT_MAX_ATTEMPTS = 5;

export const WARNINGS_CONFIG_VERSION = 1;

export const ACTIVE_WARNINGS_CARD_ROW_LIMIT = 10;
